### PR TITLE
feat: add webLN

### PR DESCRIPTION
**Pull request by rolznz**
Hi, I'm Roland from [Alby](https://getalby.com/) and as part of working on the lightning extension we are also working on improving the WebLN spec, and thought your app UX could be improved by integrating WebLN. This PR enables users to connect to a Lightning extension to get their node public key and pay the invoice without having to copy-paste.

Integrating [WebLN](https://webln.guide/) could also allow for further improvements, such as allowing users to connect their channel directly through the channel.ninja frontend using the new webln.request() function. I'm working on a demo sandbox for it here: https://rolznz.github.io/webln-sandbox/

### CODE REVIEW

**Comment by braunnicholas** [comment]
Thanks for your pull request. I will have a look at it on the weekend!

**Comment by channelninja** [comment]
Thanks for your pull request!

I didn't know about webLN until now, but from a quick look it looks interesting.

I'm a bit busy right now with work so I'll have a closer look on the weekend.

**Comment by rolznz** [comment]
@channelninja thanks! when and how did you get the error? at build time or just as a warning in your IDE? (if so which IDE did you use?)

I will try to reproduce and fix the issue.

**Comment by channelninja** [comment]
@rolznz I got it during build time. My IDE (vs code) didn’t show any errors.

**Comment by rolznz** [comment]
@channelninja I have updated the README at https://www.npmjs.com/package/@webbtc/webln-types with instructions based on how react-scripts does it (client/src/react-app-env.d.ts)

Thanks for letting me know!

**Pull request merged**
